const defaultMovies = [
  {
    id: "5bc11548-32e7-47c6-9952-71ead60e0774",
    title: "🦹‍♀️ Marvel Movies",
    movies: [
      {
        id: 429617,
        title: "Spider-Man: Far from Home",
        summary:
          "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
        image: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
        year: "2019",
        genres: "Action, Adventure, Science Fiction",
        isWatched: true,
        isFavorite: false,
      },
      {
        id: 299534,
        title: "Avengers: Endgame",
        summary:
          "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        image: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        year: "2019",
        genres: "Adventure, Science Fiction, Action",
        isWatched: true,
        isFavorite: true,
      },
      {
        id: 299536,
        title: "Avengers: Infinity War",
        summary:
          "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
        image: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        year: "2018",
        genres: "Adventure, Action, Science Fiction",
        isWatched: true,
        isFavorite: true,
      },
      {
        id: 363088,
        title: "Ant-Man and the Wasp",
        summary:
          "Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.",
        image: "/gMEtbUQGgUHwdo8d4ZpdOer3Nxu.jpg",
        year: "2018",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 284053,
        title: "Thor: Ragnarok",
        summary:
          "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.",
        image: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
        year: "2017",
        genres: "Action, Adventure, Comedy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 284054,
        title: "Black Panther",
        summary:
          "King T'Challa returns home from America to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantel to join with girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
        image: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
        year: "2018",
        genres: "Action, Adventure, Fantasy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 284052,
        title: "Doctor Strange",
        summary:
          "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
        image: "/uZpmwyfL6sIq0yzn5Dbar8QXRNa.jpg",
        year: "2016",
        genres: "Action, Adventure, Fantasy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 315635,
        title: "Spider-Man: Homecoming",
        summary:
          "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
        image: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
        year: "2017",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 271110,
        title: "Captain America: Civil War",
        summary:
          "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
        image: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
        year: "2016",
        genres: "Adventure, Action, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 102899,
        title: "Ant-Man",
        summary:
          "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
        image: "/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
        year: "2015",
        genres: "Science Fiction, Action, Adventure",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 99861,
        title: "Avengers: Age of Ultron",
        summary:
          "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
        image: "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
        year: "2015",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 283995,
        title: "Guardians of the Galaxy Vol. 2",
        summary:
          "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
        image: "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
        year: "2017",
        genres: "Action, Adventure, Comedy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 118340,
        title: "Guardians of the Galaxy",
        summary:
          "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
        image: "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
        year: "2014",
        genres: "Action, Science Fiction, Adventure",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 100402,
        title: "Captain America: The Winter Soldier",
        summary:
          "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
        image: "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
        year: "2014",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 76338,
        title: "Thor: The Dark World",
        summary:
          "Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.",
        image: "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
        year: "2013",
        genres: "Action, Adventure, Fantasy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 68721,
        title: "Iron Man 3",
        summary:
          "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
        image: "/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
        year: "2013",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 24428,
        title: "The Avengers",
        summary:
          "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
        image: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        year: "2012",
        genres: "Science Fiction, Action, Adventure",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 10195,
        title: "Thor",
        summary:
          "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
        image: "/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
        year: "2011",
        genres: "Adventure, Fantasy, Action",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 1724,
        title: "The Incredible Hulk",
        summary:
          "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.",
        image: "/2nBpExDoInX3VreBsIm9qOTqXs8.jpg",
        year: "2008",
        genres: "Science Fiction, Action, Adventure",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 10138,
        title: "Iron Man 2",
        summary:
          "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
        image: "/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
        year: "2010",
        genres: "Adventure, Action, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 1726,
        title: "Iron Man",
        summary:
          "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
        image: "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
        year: "2008",
        genres: "Action, Science Fiction, Adventure",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 299537,
        title: "Captain Marvel",
        summary:
          "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
        image: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
        year: "2019",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 1771,
        title: "Captain America: The First Avenger",
        summary:
          "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
        image: "/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
        year: "2011",
        genres: "Action, Adventure, Science Fiction",
        isWatched: false,
        isFavorite: false,
      },
    ],
  },
  {
    id: "209a4dd7-adb7-43cd-9740-a3e4c4218e69",
    title: "🧛‍♂️ Spooky Horror",
    movies: [
      {
        id: 493922,
        title: "Hereditary",
        summary:
          "When Ellen, the matriarch of the Graham family, passes away, her daughter's family begins to unravel cryptic and increasingly terrifying secrets about their ancestry.",
        image: "/lHV8HHlhwNup2VbpiACtlKzaGIQ.jpg",
        year: "2018",
        genres: "Horror, Mystery, Thriller",
        isWatched: true,
        isFavorite: true,
      },
      {
        id: 530385,
        title: "Midsommar",
        summary:
          "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.",
        image: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
        year: "2019",
        genres: "Horror, Drama, Mystery",
        isWatched: true,
        isFavorite: true,
      },
      {
        id: 270303,
        title: "It Follows",
        summary:
          "After carefree teenager Jay sleeps with her new boyfriend, Hugh, for the first time, she learns that she is the latest recipient of a fatal curse that is passed from victim to victim via sexual intercourse. Death, Jay learns, will creep inexorably toward her as either a friend or a stranger. Jay's friends don't believe her seemingly paranoid ravings, until they too begin to see the phantom assassins and band together to help her flee or defend herself.",
        image: "/kdxZZ04HFh98ZZBiTZNWHMexsGZ.jpg",
        year: "2014",
        genres: "Horror",
        isWatched: true,
        isFavorite: false,
      },
      {
        id: 805,
        title: "Rosemary's Baby",
        summary:
          "A young couple moves into an infamous New York apartment building to start a family. Things become frightening as Rosemary begins to suspect her unborn baby isn’t safe around their strange neighbors.",
        image: "/rDBHzuuA5uFrc9KbsksrsPvuzgA.jpg",
        year: "1968",
        genres: "Horror, Drama, Mystery",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 11906,
        title: "Suspiria",
        summary:
          "An American newcomer to a prestigious German ballet academy comes to realize that the school is a front for something sinister amid a series of grisly murders.",
        image: "/5ya8jTbNZTrCFUx9OwpNBjCivXY.jpg",
        year: "1977",
        genres: "Horror",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 310131,
        title: "The Witch",
        summary:
          "In 1630s New England, William and Katherine lead a devout Christian life with five children, homesteading on the edge of an impassable wilderness, exiled from their settlement when William defies the local church. When their newborn son vanishes and crops mysteriously fail, the family turns on one another.",
        image: "/o384OC1tCV8nCnozkM6y4MiSqsw.jpg",
        year: "2015",
        genres: "Horror, Drama, Mystery",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 346364,
        title: "It",
        summary:
          "In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.",
        image: "/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
        year: "2017",
        genres: "Horror",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 474350,
        title: "It Chapter Two",
        summary:
          "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
        image: "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
        year: "2019",
        genres: "Horror, Fantasy",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 419430,
        title: "Get Out",
        summary:
          "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
        image: "/qbaIViX3tgWSTSFXbldq0ODMdi4.jpg",
        year: "2017",
        genres: "Mystery, Thriller, Horror",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 694,
        title: "The Shining",
        summary:
          "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
        image: "/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
        year: "1980",
        genres: "Horror, Thriller",
        isWatched: false,
        isFavorite: false,
      },
      {
        id: 9552,
        title: "The Exorcist",
        summary:
          "12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.",
        image: "/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg",
        year: "1973",
        genres: "Horror",
        isWatched: false,
        isFavorite: false,
      },
    ],
  },
];

export default defaultMovies;
